name: videoprocgpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.0
  - opencv=4.5.1
  - python-dotenv=0.17.0
  - pika=1.2.0
  - cudatoolkit=10.1
  - pytorch=1.7.0
  - pip= 21.0.1
  - pip:
    - dataclasses==0.6
    - future==0.18.2  
    - mxnet-cu101==1.5.0
    - gluoncv==0.10.1
