version: "3.0"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: aidl_rabbitmq
    hostname: aidl-rabbitmq
    volumes:
      - /opt/aidl/data/rabbitmq:/var/lib/rabbitmq
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PW}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      default:
        aliases:
          - aidl_rabbitmq
